language: php
php:
- '7.1'
- '7.2'
before_install:
- travis_retry composer self-update
install:
- composer update --prefer-lowest --no-interaction
script:
- bin/phpunit
- composer update --no-dev
- wget https://github.com/clue/phar-composer/releases/download/v1.0.0/phar-composer.phar
- chmod +x phar-composer.phar
- sed -s "s/{version}/$( git describe --tags )/" bin/plumbok.php > bin/plumbok.php
- php -d phar.readonly=Off phar-composer.phar build
deploy:
  provider: releases
  api_key:
    secure: "lUG3HtURHf7WNllWUZCclKQP0BZtXvA87HNRfrDeTPrgjy5IXRdf+WjegwTD/pHFRwfjsEJUmwj+g3+rK7/trmqwZdOtaGd0k1CsmzFJH395FtG2mmvb4o2vRItOa8vlhqXbkBsoiOZOVCSlQ3LD2FMxxY2w1CwDiU98/YIvEs3XE0uBnPNgELbXxDw/nbCC+czok47HLuRoCWvxRfGXunrhjUCUse3skZIfRfT1TAhmlHIvA4HN9JvDgcrLQ7mdZbNtHN4uOhrhSLYJ3/zIVmykvMA4h88aw+wUWSpgSckyaN7agoVV68maic3cIjUmLvgV2fP3b2wx9zXco2B3lrkRmTcndKkdJYBQvFOBaFRcO33lHvFhBMSfNlCWXmmDK0yC8TfxShI42aatLjnX5XwUMLU5VUhjApBd+r6FYmNy/m88bSyuoRF1iskrj0bc5ppCq7Ch+/D5wGXEl8kmRuxfZgKW82NipGyV/eNx30BB/vojrmR5EH7Iu6l3ksphhrDAW2YvPqW1y3bmGL9AG/CEj4go0Om2wJfAGlfYyasRI7ahAR6w3b7k9Tg8yTSya40mKJ3unU+XquvVcGk00naYyQ9QhUUfxGNMSLQpexgBn8v4ZhBBCFL1N6ZuvQJgDPu9a9aYCeA6ogIQaqYBMydNhEItIHNl+ZT0PZM1Ryo="
  file: plumbok.phar
  on:
    repo: plumbok/plumbok
    php: 7.1
    tags: true
notifications:
  on_success: never
  on_failure: always
env:
  global:
    secure: "lUG3HtURHf7WNllWUZCclKQP0BZtXvA87HNRfrDeTPrgjy5IXRdf+WjegwTD/pHFRwfjsEJUmwj+g3+rK7/trmqwZdOtaGd0k1CsmzFJH395FtG2mmvb4o2vRItOa8vlhqXbkBsoiOZOVCSlQ3LD2FMxxY2w1CwDiU98/YIvEs3XE0uBnPNgELbXxDw/nbCC+czok47HLuRoCWvxRfGXunrhjUCUse3skZIfRfT1TAhmlHIvA4HN9JvDgcrLQ7mdZbNtHN4uOhrhSLYJ3/zIVmykvMA4h88aw+wUWSpgSckyaN7agoVV68maic3cIjUmLvgV2fP3b2wx9zXco2B3lrkRmTcndKkdJYBQvFOBaFRcO33lHvFhBMSfNlCWXmmDK0yC8TfxShI42aatLjnX5XwUMLU5VUhjApBd+r6FYmNy/m88bSyuoRF1iskrj0bc5ppCq7Ch+/D5wGXEl8kmRuxfZgKW82NipGyV/eNx30BB/vojrmR5EH7Iu6l3ksphhrDAW2YvPqW1y3bmGL9AG/CEj4go0Om2wJfAGlfYyasRI7ahAR6w3b7k9Tg8yTSya40mKJ3unU+XquvVcGk00naYyQ9QhUUfxGNMSLQpexgBn8v4ZhBBCFL1N6ZuvQJgDPu9a9aYCeA6ogIQaqYBMydNhEItIHNl+ZT0PZM1Ryo="

