language: php
php:
- '7.0'
- '7.1'
- nightly
before_install:
- travis_retry composer self-update
install:
- composer update --prefer-lowest --no-interaction
script:
- bin/phpunit
- composer update --no-dev
- wget https://github.com/clue/phar-composer/releases/download/v1.0.0/phar-composer.phar
- chmod +x phar-composer.phar
- sed -s "s/{version}/$( git describe --tags )/" bin/plumbok.php
- php -d phar.readonly=Off phar-composer.phar build
deploy:
  provider: releases
  api_key:
    secure: rjs5H/+mHu/QHFJPNI2ooMgww8XWq1fWL5k7eUAFooHUhjZ/a7G99Cd81b3kRLe8Pl9xBZNuNzZ4pp8EjgGucIGzmE/TQzBcch+2lMSIyBb0OG3POKkuKTphIVsrfjeYXQPzv1/DWK/4hgF+hQyx6IJk1hr9rfuXrunNZbzOQnCKAGOsICqfq9H8VP6N+donz1/DooBLp/4z4RB6Y7/O5rqvdCGMpZf68DcObG/swAuv9yFf7hw4S4GSgsW44iWj0/GB8+mUEaT+QYNI8iAeAO7c0PZGCDBUpTZkb0wi8/h3AmI6RaEO5ADNdWHApEy/FppYK9RchA2rk2PznT1CEZDneHaCDYvguX2HgqnReDxOd3aQjvGXMGKB/H4gVlLUVzWXfH22Q2FuuYWhdEuzLZONlQxbWid5H2sB76s1BUMmnB0tIkvJ/06GInL2rSpVICUgbGcdRF3EPpadZOydWzkFnEdPQYOU9t0DH+ZSawWPPGYdR7UfCAMPBh3ZNTiUW9dyFEACqJkGpU/PhWOEwwnWHhGqmhtvruGyDb36JGa0yBG18uCegJn090vYQ3dgoL9A/qbi5Sia2vpKq4RijqCp1L5yLE6/43t0SxdX+HO2p6fpfSaiPA/DvjDnQ46TovpUkvKKc6qjwpjcJDlr68tClYSOpjeEK5XPa9HnAfM=
  file: plumbok.phar
  on:
    repo: plumbok/plumbok
    php: 7.0
    tags: true
notifications:
  on_success: never
  on_failure: always
