language: php

php:
  - '7.0'
  - '7.1'
  - nightly

env:
  - COMPOSER_FLAGS="--prefer-lowest"

before_install:
  - travis_retry composer self-update

install:
  - composer update $COMPOSER_FLAGS --no-interaction

script: bin/phpunit

before_deploy:
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - php -d phar.readonly=Off ${ which box } build

deploy:
  provider: releases
  file: plumbok.phar
  user: brzuchal
  password:
    secure: JNZOzgKqUYdcvvGVHn1Si8g2tXyXvgwXL5wmbL54gL2sdF+offEMpv3+vU1dswAoXD/H+/R+nDdAKTOIaOfRfNFqZjxYz/hxZzyAwePIj7FYtc/Adtf7JYc77sr3nRgg/0h1NiZC5ntSfh0nmZgE8ThdIARDxO2J+RbLAdX4FP/Kt7MIYq6+kWTYnuxpcJej6+tK919dJ2/ZDe9P6uB7r4WL3kP9L1cKYoqqQ+qZrBFix6YirQwxFDEDhWyM/fnyd6EinoaLJd7+0QPvbUa6Fm16XiuuZGmhETBe8LK0RS5F1PUdBiqeKKOGrHF0jsO3XHFpQ04xcrrdit+AKuP49m/6zwQWO0g1Suq+iVSo99jl1jaAb0wdPWT1V0/aOtCexfXm6KH7syYe+9T6OW+ujbhXhKrdz/u5e2UD7Ur1OcA17IWF4nIYWm3Js1oI4YTUCc0+EtVDLflk+nIn223l25qZCQG6dDcx8uZnxWwNtt944tjnQ7RnvEWYCzTzh7CIc05c8nLgkfDGxhDWX+MbjjcwU9sJsUH9hjn9gQnp81cJt988EAQhWLWYtd9B14cfjaprAweqRXj/AzkJrdeZTIbEzMjsFwULcWYnuCLHniRi3lS1IYsQMvr9lMA1g11A3ToODJWLlx26CeynWHdLcwTBMHZ9WdLf59amQBz+HPI=
  skip_cleanup: true
  on:
    repo: plumbok/plumbok
    php: 7.0
    tags: true
    condition: "$COMPOSER_FLAGS = --prefer-lowest"

notifications:
  on_success: never
  on_failure: always
